version: 2

sources:
  - name: silver_layer
    schema: silver
    tables:
      - name: crypto_prices
        config:
          external_location: '/opt/data/silver/**/*.parquet'

#duckdb moze czytac ze sciezki wiec nie trzeba uzywac dbt stage_external_sources