version: '3.8'
x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../data:/opt/data
    - ../scripts:/opt/airflow/scripts
    - ../dbt_crypto:/opt/airflow/dbt_crypto
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - dbt-init

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - dbt-init

  dbt-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create  --username admin  --firstname admin  --lastname admin  --role Admin  --email admin@example.com  --password admin && cd /opt/airflow/dbt_crypto && dbt deps"

  crypto_dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    container_name: crypto_dashboard
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ../dbt_crypto:/dbt_crypto
    depends_on:
      - webserver
volumes:
  postgres_data:
